CREATE OR REPLACE VIEW VW_COLABORADORES_ATIVOS AS
SELECT
    ID_COLABORADOR,
    NOME,
    EMAIL,
    HABILIDADES,
    MODELO_TRABALHO,
    NIVEL_IA,
    DATA_CRIACAO,
    DATA_ATUALIZACAO
FROM TB_COLABORADORES
WHERE ATIVO = 1
ORDER BY NOME;

COMMENT ON TABLE VW_COLABORADORES_ATIVOS IS 'View com apenas colaboradores ativos';

-- ============================================
-- 2. VIEW - ESTATÍSTICAS POR MODELO DE TRABALHO
-- ============================================
CREATE OR REPLACE VIEW VW_STATS_MODELO_TRABALHO AS
SELECT
    MODELO_TRABALHO,
    COUNT(*) AS TOTAL_COLABORADORES,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM TB_COLABORADORES WHERE ATIVO = 1), 2) AS PERCENTUAL
FROM TB_COLABORADORES
WHERE ATIVO = 1
GROUP BY MODELO_TRABALHO
ORDER BY TOTAL_COLABORADORES DESC;

COMMENT ON TABLE VW_STATS_MODELO_TRABALHO IS 'Estatísticas de colaboradores por modelo de trabalho';

-- ============================================
-- 3. VIEW - ESTATÍSTICAS POR NÍVEL DE IA
-- ============================================
CREATE OR REPLACE VIEW VW_STATS_NIVEL_IA AS
SELECT
    NIVEL_IA,
    COUNT(*) AS TOTAL_COLABORADORES,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM TB_COLABORADORES WHERE ATIVO = 1), 2) AS PERCENTUAL
FROM TB_COLABORADORES
WHERE ATIVO = 1
GROUP BY NIVEL_IA
ORDER BY
    CASE NIVEL_IA
        WHEN 'INICIANTE' THEN 1
        WHEN 'USUARIO' THEN 2
        WHEN 'PARCEIRO' THEN 3
        WHEN 'ESPECIALISTA' THEN 4
        END;

COMMENT ON TABLE VW_STATS_NIVEL_IA IS 'Estatísticas de colaboradores por nível de IA';

-- ============================================
-- 4. VIEW - COLABORADORES REMOTOS
-- ============================================
CREATE OR REPLACE VIEW VW_COLABORADORES_REMOTOS AS
SELECT
    ID_COLABORADOR,
    NOME,
    EMAIL,
    HABILIDADES,
    NIVEL_IA,
    DATA_CRIACAO
FROM TB_COLABORADORES
WHERE MODELO_TRABALHO = 'REMOTO' AND ATIVO = 1
ORDER BY NOME;

COMMENT ON TABLE VW_COLABORADORES_REMOTOS IS 'Lista de colaboradores que trabalham remotamente';

-- ============================================
-- 5. VIEW - ESPECIALISTAS EM IA
-- ============================================
CREATE OR REPLACE VIEW VW_ESPECIALISTAS_IA AS
SELECT
    ID_COLABORADOR,
    NOME,
    EMAIL,
    HABILIDADES,
    MODELO_TRABALHO,
    DATA_CRIACAO
FROM TB_COLABORADORES
WHERE NIVEL_IA = 'ESPECIALISTA' AND ATIVO = 1
ORDER BY NOME;

COMMENT ON TABLE VW_ESPECIALISTAS_IA IS 'Colaboradores com nível especialista em IA';

-- ============================================
-- 6. VIEW - DASHBOARD EXECUTIVO
-- ============================================
CREATE OR REPLACE VIEW VW_DASHBOARD_EXECUTIVO AS
SELECT
    (SELECT COUNT(*) FROM TB_COLABORADORES WHERE ATIVO = 1) AS TOTAL_ATIVOS,
    (SELECT COUNT(*) FROM TB_COLABORADORES WHERE ATIVO = 0) AS TOTAL_INATIVOS,
    (SELECT COUNT(*) FROM TB_COLABORADORES WHERE MODELO_TRABALHO = 'REMOTO' AND ATIVO = 1) AS TOTAL_REMOTOS,
    (SELECT COUNT(*) FROM TB_COLABORADORES WHERE MODELO_TRABALHO = 'HIBRIDO' AND ATIVO = 1) AS TOTAL_HIBRIDOS,
    (SELECT COUNT(*) FROM TB_COLABORADORES WHERE MODELO_TRABALHO = 'PRESENCIAL' AND ATIVO = 1) AS TOTAL_PRESENCIAIS,
    (SELECT COUNT(*) FROM TB_COLABORADORES WHERE NIVEL_IA = 'INICIANTE' AND ATIVO = 1) AS TOTAL_INICIANTES,
    (SELECT COUNT(*) FROM TB_COLABORADORES WHERE NIVEL_IA = 'USUARIO' AND ATIVO = 1) AS TOTAL_USUARIOS,
    (SELECT COUNT(*) FROM TB_COLABORADORES WHERE NIVEL_IA = 'PARCEIRO' AND ATIVO = 1) AS TOTAL_PARCEIROS,
    (SELECT COUNT(*) FROM TB_COLABORADORES WHERE NIVEL_IA = 'ESPECIALISTA' AND ATIVO = 1) AS TOTAL_ESPECIALISTAS
FROM DUAL;

COMMENT ON TABLE VW_DASHBOARD_EXECUTIVO IS 'Dashboard com números consolidados';

-- ============================================
-- 7. VIEW - COLABORADORES RECENTES
-- ============================================
CREATE OR REPLACE VIEW VW_COLABORADORES_RECENTES AS
SELECT
    ID_COLABORADOR,
    NOME,
    EMAIL,
    MODELO_TRABALHO,
    NIVEL_IA,
    DATA_CRIACAO,
    TRUNC(SYSDATE - DATA_CRIACAO) AS DIAS_DESDE_CRIACAO
FROM TB_COLABORADORES
WHERE ATIVO = 1
  AND DATA_CRIACAO >= SYSDATE - 30
ORDER BY DATA_CRIACAO DESC;

COMMENT ON TABLE VW_COLABORADORES_RECENTES IS 'Colaboradores criados nos últimos 30 dias';

-- ============================================
-- 8. VIEW - RELATÓRIO COMPLETO
-- ============================================
CREATE OR REPLACE VIEW VW_RELATORIO_COMPLETO AS
SELECT
    c.ID_COLABORADOR,
    c.NOME,
    c.EMAIL,
    c.HABILIDADES,
    c.MODELO_TRABALHO,
    CASE c.MODELO_TRABALHO
        WHEN 'REMOTO' THEN '🏠 Remoto'
        WHEN 'HIBRIDO' THEN '🔄 Híbrido'
        WHEN 'PRESENCIAL' THEN '🏢 Presencial'
        END AS MODELO_DESCRICAO,
    c.NIVEL_IA,
    CASE c.NIVEL_IA
        WHEN 'INICIANTE' THEN '⭐ Iniciante'
        WHEN 'USUARIO' THEN '⭐⭐ Usuário'
        WHEN 'PARCEIRO' THEN '⭐⭐⭐ Parceiro'
        WHEN 'ESPECIALISTA' THEN '⭐⭐⭐⭐ Especialista'
        END AS NIVEL_DESCRICAO,
    TO_CHAR(c.DATA_CRIACAO, 'DD/MM/YYYY HH24:MI:SS') AS DATA_CADASTRO,
    TO_CHAR(c.DATA_ATUALIZACAO, 'DD/MM/YYYY HH24:MI:SS') AS ULTIMA_ATUALIZACAO,
    TRUNC(SYSDATE - c.DATA_CRIACAO) AS DIAS_NO_SISTEMA
FROM TB_COLABORADORES c
WHERE c.ATIVO = 1
ORDER BY c.NOME;

COMMENT ON TABLE VW_RELATORIO_COMPLETO IS 'Relatório completo formatado para apresentação';

-- ============================================
-- 9. VIEW - HABILIDADES MAIS COMUNS
-- ============================================
-- Esta view extrai e conta habilidades individuais
-- Útil para análise de competências mais requisitadas
CREATE OR REPLACE VIEW VW_HABILIDADES_POPULARES AS
SELECT
    TRIM(REGEXP_SUBSTR(HABILIDADES, '[^,]+', 1, LEVEL)) AS HABILIDADE,
    COUNT(*) AS TOTAL_COLABORADORES
FROM TB_COLABORADORES
WHERE ATIVO = 1
    CONNECT BY LEVEL <= REGEXP_COUNT(HABILIDADES, ',') + 1
    AND PRIOR ID_COLABORADOR = ID_COLABORADOR
    AND PRIOR DBMS_RANDOM.VALUE IS NOT NULL
GROUP BY TRIM(REGEXP_SUBSTR(HABILIDADES, '[^,]+', 1, LEVEL))
HAVING COUNT(*) > 1
ORDER BY TOTAL_COLABORADORES DESC, HABILIDADE;

COMMENT ON TABLE VW_HABILIDADES_POPULARES IS 'Habilidades mais frequentes entre colaboradores';

-- ============================================
-- 10. VIEW - AUDITORIA (ÚLTIMAS ALTERAÇÕES)
-- ============================================
CREATE OR REPLACE VIEW VW_ULTIMAS_ALTERACOES AS
SELECT
    ID_COLABORADOR,
    NOME,
    EMAIL,
    MODELO_TRABALHO,
    NIVEL_IA,
    DATA_ATUALIZACAO,
    TRUNC((SYSDATE - DATA_ATUALIZACAO) * 24) AS HORAS_DESDE_ALTERACAO
FROM TB_COLABORADORES
WHERE ATIVO = 1
  AND DATA_ATUALIZACAO > DATA_CRIACAO
ORDER BY DATA_ATUALIZACAO DESC;

COMMENT ON TABLE VW_ULTIMAS_ALTERACOES IS 'Colaboradores recentemente atualizados';

-- ============================================
-- EXEMPLOS DE CONSULTAS NAS VIEWS
-- ============================================

-- Exemplo 1: Dashboard executivo
-- SELECT * FROM VW_DASHBOARD_EXECUTIVO;

-- Exemplo 2: Estatísticas por modelo
-- SELECT * FROM VW_STATS_MODELO_TRABALHO;

-- Exemplo 3: Top 10 habilidades
-- SELECT * FROM VW_HABILIDADES_POPULARES WHERE ROWNUM <= 10;

-- Exemplo 4: Relatório completo
-- SELECT * FROM VW_RELATORIO_COMPLETO;

-- ============================================
-- VERIFICAÇÃO
-- ============================================
SELECT 'Views criadas com sucesso!' AS STATUS FROM DUAL;

SELECT VIEW_NAME, TEXT_LENGTH
FROM USER_VIEWS
WHERE VIEW_NAME LIKE 'VW_%'
ORDER BY VIEW_NAME;

PROMPT
PROMPT Total de Views Criadas:
SELECT COUNT(*) AS TOTAL_VIEWS
FROM USER_VIEWS
WHERE VIEW_NAME LIKE 'VW_%';